pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/MesVortex/SecurePro.git'
            }
        }
        stage('Build') {
                    steps {
                        // Fix: Ensure `mvnw` has executable permissions
                        sh 'chmod +x ./mvnw'
                        // Use Maven to build the project
                        sh './mvnw clean package -DskipTests'
                    }
                }
        stage('Docker Build and Push') {
            steps {
                script {

                    def dockerImage = docker.build("${DOCKER_IMAGE}:${env.BUILD_NUMBER}")

                    dockerImage.push("${env.BUILD_NUMBER}")
                    dockerImage.push("latest")
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'docker-compose down'

                    sh """
                    docker-compose up -d --build
                    """
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline completed.'
        }
        success {
            echo 'Pipeline succeeded.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}