pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "SecurePro"
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/MesVortex/SecurePro.git'
            }
        }
        stage('Build') {
            steps {
                sh './mvnw clean package'
            }
        }
        stage('Docker Build and Push') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}:${env.BUILD_NUMBER}").push()
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}